<center>
<h4>Universidad Nacional de Córdoba - Facultad de Matemática, Astronomía, Física y Computación</h4>
<h3>Diplomatura en Ciencia de Datos, Aprendizaje Automático y sus Aplicaciones</h3>
</center>

# ¿Cómo leer datos desde pandas?

En esta primera notebook, aprendemos cómo cargar un conjunto de datos utilizando pandas y cómo ver su contenido.

In [1]:
import io
import pandas
import seaborn

print(seaborn.__version__)

0.9.0

In [2]:
df = pandas.read_csv('C:/Users/W10/Documents/Vero-Data Science/AnalisisyVisualizacion/Dataset.csv')

Con esta operación, hemos creado un DataFrame de pandas en base al archivo de respuestas. Un DataFrame no es más que una tabla sobre la cual podemos aplicar un montón de operaciones similares a las de Excel o a las SQL. En esta notebook no pretendemos hacer un tutorial de pandas, el Internet está lleno de ellos, pero sí iremos explicando cómo implementar determinadas operaciones necesarias para el análisis de este conjunto de datos.

Veamos qué tiene adentro el DataFrame `df`.

In [4]:
df

,Marca temporal,¿Con qué género te identificás?,¿Qué edad tenés?,¿De qué signo sos?,¿A qué te dedicás?,¿Cuánto creés que gana por mes un programador (con dos o menos años de experiencia) en la industria argentina?,¿Cuánto creés que gana por mes un programador (con tres o más años de experiencia) en la industria argentina?
0,31/03/2020 17:10:01,Mujer,27,Tauro,Programadora,40000.0,80000.0
1,12/05/2020 15:19:14,Mujer,40,Acuario,Docente investigadora,50000.0,90000.0
2,13/05/2020 13:43:48,Hombre,22,Géminis,Estudiante de Astronomía,25000.0,60000.0
3,13/05/2020 18:12:04,Mujer,23,Cáncer,profesora,32000.0,50000.0
4,14/05/2020 16:30:09,Hombre,33,Capricornio,Docente investigador,60000.0,80000.0
5,14/05/2020 19:46:32,Hombre,29,Sagitario,Ingenieria de circuitos integrados,55000.0,75000.0
6,14/05/2020 19:46:57,Hombre,36,Libra,Emprendedor,50000.0,80000.0
7,14/05/2020 19:49:24,Hombre,28,Cáncer,Diseñador de circuitos digitales,50000.0,60000.0
8,14/05/2020 19:53:12,Hombre,39,Escorpio,programador,100000.0,150000.0
9,14/05/2020 19:54:35,Hombre,28,Géminis,Estudiante de Sociología,40000.0,60000.0
10,14/05/2020 19:57:29,Hombre,33,Acuario,investigador-docente,60000.0,80000.0
11,14/05/2020 20:00:52,Hombre,29,Virgo,Analista de Datos,50000.0,90000.0
12,14/05/2020 20:17:37,Hombre,25,Libra,Economista,50000.0,80000.0
13,14/05/2020 20:29:10,Hombre,36,Libra,programador,40000.0,50000.0
14,14/05/2020 20:41:58,Hombre,30,Sagitario,Programador,30000.0,45000.0
15,14/05/2020 21:06:36,Hombre,27,Aries,Estudiante de ingeniería,50000.0,90000.0
16,14/05/2020 21:10:10,Hombre,26,Libra,Programador,50000.0,90000.0
17,14/05/2020 21:16:43,Hombre,25,Aries,Programador,40000.0,60000.0
18,14/05/2020 21:40:58,Mujer,27,Aries,economista,65000.0,90000.0
19,14/05/2020 21:41:22,Hombre,36,Leo,programador,50000.0,70000.0
20,14/05/2020 21:56:20,Hombre,28,Virgo,Empleado,70000.0,125000.0
21,14/05/2020 21:58:39,Mujer,27,Picis,Economista,55000.0,80000.0
22,14/05/2020 22:12:19,Hombre,47,Escorpio,Gestión,60000.0,90000.0
23,14/05/2020 22:27:18,Hombre,26,Géminis,Programador,40000.0,70000.0
24,14/05/2020 22:55:06,Mujer,30,Picis,Analista de Datos,60000.0,75000.0
25,14/05/2020 23:04:03,Hombre,39,Capricornio,programador,50000.0,80000.0
26,15/05/2020 7:41:14,Hombre,42,Escorpio,docente,40000.0,70000.0
27,15/05/2020 8:56:45,Hombre,46,Picis,Programador,50000.0,75000.0
28,15/05/2020 9:10:49,Hombre,51,Géminis,Varios,20000.0,35000.0
29,15/05/2020 9:11:50,Hombre,23,Leo,Programador,60000.0,90000.0
...,...,...,...,...,...,...,...
119,22/05/2020 18:21:54,Hombre,28,Virgo,Biólogo,50000.0,60000.0
120,22/05/2020 18:22:06,Mujer,30,Picis,Doctora en Ciencias Biológicas,40000.0,80000.0
121,22/05/2020 18:22:07,Hombre,31,Géminis,Analista De Sistemas,60000.0,80000.0
122,22/05/2020 18:22:13,Mujer,55,Géminis,profesora,40000.0,80000.0
123,22/05/2020 18:22:17,Mujer,52,Leo,Ingeniera,40000.0,60000.0
124,22/05/2020 18:22:20,Hombre,27,Picis,Estudiante,40000.0,80000.0
125,22/05/2020 18:22:23,Hombre,25,Picis,Economista,50000.0,80000.0
126,22/05/2020 18:22:25,Mujer,27,Aries,Analista en computacion,50000.0,90000.0
127,22/05/2020 18:22:32,Mujer,24,Capricornio,Estudiante de Ciencias de la Computación,40000.0,55000.0
128,22/05/2020 18:22:34,Prefiero no decirlo,60,Cáncer,Jubilada,25000.0,50000.0
129,22/05/2020 18:22:40,Hombre,49,Tauro,Bioingeniero,50000.0,100000.0
130,22/05/2020 18:22:47,Hombre,22,Virgo,Estudiante ingeniería electrónica,50000.0,100000.0
131,22/05/2020 18:22:53,Mujer,35,Géminis,estudiante de postgrado,80000.0,120000.0
132,22/05/2020 18:22:56,Hombre,25,Capricornio,Desarrollador de Software,60000.0,90000.0
133,22/05/2020 18:23:06,Hombre,39,Sagitario,sistemas,60000.0,90000.0
134,22/05/2020 18:23:08,Hombre,27,Cáncer,abogado,35000.0,70000.0
135,22/05/2020 18:23:11,Prefiero no decirlo,40,Leo,Lic,40000.0,80000.0
136,22/05/2020 18:23:31,Hombre,41,Géminis,Sistemas,50000.0,110000.0
137,22/05/2020 18:23:33,Mujer,33,Aries,psicologa,70.0,90.0
138,22/05/2020 18:23:34,Hombre,31,Géminis,Ing. en Sistemas,45000.0,60000.0
139,22/05/2020 18:23:45,Prefiero no decirlo,25,Picis,Ingenieria,70000.0,100000.0
140,22/05/2020 18:23:50,Otro,17,Picis,estudiante,35000.0,150000.0
141,22/05/2020 18:23:58,Hombre,25,Capricornio,Programador,40000.0,75000.0
142,22/05/2020 18:24:10,Hombre,26,Acuario,Desarrollador,50000.0,70000.0
143,22/05/2020 18:24:44,Mujer,32,Cáncer,Profesora,45000.0,50000.0
144,22/05/2020 18:25:01,Hombre,49,Aries,Ingeniero de Software,40000.0,55000.0
145,22/05/2020 18:25:27,Mujer,62,Aries,Arquitecta,60000.0,80000.0
146,22/05/2020 18:25:58,Hombre,33,Libra,"Estudiante, programador",60000.0,80000.0
147,22/05/2020 18:26:04,Hombre,35,Picis,Desarrolador,50000.0,150000.0
148,22/05/2020 18:28:19,Mujer,36,Géminis,Docente,50000.0,100000.0

In [3]:
df.columns

Index(['Marca temporal', '¿Con qué género te identificás?', '¿Qué edad tenés?',
       '¿De qué signo sos?', '¿A qué te dedicás?',
       '¿Cuánto creés que gana por mes un programador (con dos o menos años de experiencia) en la industria argentina?',
       '¿Cuánto creés que gana por mes un programador (con tres o más años de experiencia) en la industria argentina?'],
      dtype='object')

In [6]:
len(df)

149

In [7]:
df['Marca temporal']

0      31/03/2020 17:10:01
1      12/05/2020 15:19:14
2      13/05/2020 13:43:48
3      13/05/2020 18:12:04
4      14/05/2020 16:30:09
5      14/05/2020 19:46:32
6      14/05/2020 19:46:57
7      14/05/2020 19:49:24
8      14/05/2020 19:53:12
9      14/05/2020 19:54:35
10     14/05/2020 19:57:29
11     14/05/2020 20:00:52
12     14/05/2020 20:17:37
13     14/05/2020 20:29:10
14     14/05/2020 20:41:58
15     14/05/2020 21:06:36
16     14/05/2020 21:10:10
17     14/05/2020 21:16:43
18     14/05/2020 21:40:58
19     14/05/2020 21:41:22
20     14/05/2020 21:56:20
21     14/05/2020 21:58:39
22     14/05/2020 22:12:19
23     14/05/2020 22:27:18
24     14/05/2020 22:55:06
25     14/05/2020 23:04:03
26      15/05/2020 7:41:14
27      15/05/2020 8:56:45
28      15/05/2020 9:10:49
29      15/05/2020 9:11:50
              ...
119    22/05/2020 18:21:54
120    22/05/2020 18:22:06
121    22/05/2020 18:22:07
122    22/05/2020 18:22:13
123    22/05/2020 18:22:17
124    22/05/2020 18:22:20
125    22/05/2020 18:22:23
126    22/05/2020 18:22:25
127    22/05/2020 18:22:32
128    22/05/2020 18:22:34
129    22/05/2020 18:22:40
130    22/05/2020 18:22:47
131    22/05/2020 18:22:53
132    22/05/2020 18:22:56
133    22/05/2020 18:23:06
134    22/05/2020 18:23:08
135    22/05/2020 18:23:11
136    22/05/2020 18:23:31
137    22/05/2020 18:23:33
138    22/05/2020 18:23:34
139    22/05/2020 18:23:45
140    22/05/2020 18:23:50
141    22/05/2020 18:23:58
142    22/05/2020 18:24:10
143    22/05/2020 18:24:44
144    22/05/2020 18:25:01
145    22/05/2020 18:25:27
146    22/05/2020 18:25:58
147    22/05/2020 18:26:04
148    22/05/2020 18:28:19
Name: Marca temporal, Length: 149, dtype: object

## Variables y columnas

Para trabajar más cómodamente, renombraremos las columnas de DataFrame. Tengan cuidado de que el orden de los nombres nuevos se corresponda con el contenido de cada columna.

In [4]:
df.columns = ['timestamp', 'gender', 'age', 'zodiac_sign', 'profession', 'junior_programmer_salary', 'senior_programmer_salary']

In [5]:
df

,timestamp,gender,age,zodiac_sign,profession,junior_programmer_salary,senior_programmer_salary
0,31/03/2020 17:10:01,Mujer,27,Tauro,Programadora,40000.0,80000.0
1,12/05/2020 15:19:14,Mujer,40,Acuario,Docente investigadora,50000.0,90000.0
2,13/05/2020 13:43:48,Hombre,22,Géminis,Estudiante de Astronomía,25000.0,60000.0
3,13/05/2020 18:12:04,Mujer,23,Cáncer,profesora,32000.0,50000.0
4,14/05/2020 16:30:09,Hombre,33,Capricornio,Docente investigador,60000.0,80000.0
5,14/05/2020 19:46:32,Hombre,29,Sagitario,Ingenieria de circuitos integrados,55000.0,75000.0
6,14/05/2020 19:46:57,Hombre,36,Libra,Emprendedor,50000.0,80000.0
7,14/05/2020 19:49:24,Hombre,28,Cáncer,Diseñador de circuitos digitales,50000.0,60000.0
8,14/05/2020 19:53:12,Hombre,39,Escorpio,programador,100000.0,150000.0
9,14/05/2020 19:54:35,Hombre,28,Géminis,Estudiante de Sociología,40000.0,60000.0
10,14/05/2020 19:57:29,Hombre,33,Acuario,investigador-docente,60000.0,80000.0
11,14/05/2020 20:00:52,Hombre,29,Virgo,Analista de Datos,50000.0,90000.0
12,14/05/2020 20:17:37,Hombre,25,Libra,Economista,50000.0,80000.0
13,14/05/2020 20:29:10,Hombre,36,Libra,programador,40000.0,50000.0
14,14/05/2020 20:41:58,Hombre,30,Sagitario,Programador,30000.0,45000.0
15,14/05/2020 21:06:36,Hombre,27,Aries,Estudiante de ingeniería,50000.0,90000.0
16,14/05/2020 21:10:10,Hombre,26,Libra,Programador,50000.0,90000.0
17,14/05/2020 21:16:43,Hombre,25,Aries,Programador,40000.0,60000.0
18,14/05/2020 21:40:58,Mujer,27,Aries,economista,65000.0,90000.0
19,14/05/2020 21:41:22,Hombre,36,Leo,programador,50000.0,70000.0
20,14/05/2020 21:56:20,Hombre,28,Virgo,Empleado,70000.0,125000.0
21,14/05/2020 21:58:39,Mujer,27,Picis,Economista,55000.0,80000.0
22,14/05/2020 22:12:19,Hombre,47,Escorpio,Gestión,60000.0,90000.0
23,14/05/2020 22:27:18,Hombre,26,Géminis,Programador,40000.0,70000.0
24,14/05/2020 22:55:06,Mujer,30,Picis,Analista de Datos,60000.0,75000.0
25,14/05/2020 23:04:03,Hombre,39,Capricornio,programador,50000.0,80000.0
26,15/05/2020 7:41:14,Hombre,42,Escorpio,docente,40000.0,70000.0
27,15/05/2020 8:56:45,Hombre,46,Picis,Programador,50000.0,75000.0
28,15/05/2020 9:10:49,Hombre,51,Géminis,Varios,20000.0,35000.0
29,15/05/2020 9:11:50,Hombre,23,Leo,Programador,60000.0,90000.0
...,...,...,...,...,...,...,...
119,22/05/2020 18:21:54,Hombre,28,Virgo,Biólogo,50000.0,60000.0
120,22/05/2020 18:22:06,Mujer,30,Picis,Doctora en Ciencias Biológicas,40000.0,80000.0
121,22/05/2020 18:22:07,Hombre,31,Géminis,Analista De Sistemas,60000.0,80000.0
122,22/05/2020 18:22:13,Mujer,55,Géminis,profesora,40000.0,80000.0
123,22/05/2020 18:22:17,Mujer,52,Leo,Ingeniera,40000.0,60000.0
124,22/05/2020 18:22:20,Hombre,27,Picis,Estudiante,40000.0,80000.0
125,22/05/2020 18:22:23,Hombre,25,Picis,Economista,50000.0,80000.0
126,22/05/2020 18:22:25,Mujer,27,Aries,Analista en computacion,50000.0,90000.0
127,22/05/2020 18:22:32,Mujer,24,Capricornio,Estudiante de Ciencias de la Computación,40000.0,55000.0
128,22/05/2020 18:22:34,Prefiero no decirlo,60,Cáncer,Jubilada,25000.0,50000.0
129,22/05/2020 18:22:40,Hombre,49,Tauro,Bioingeniero,50000.0,100000.0
130,22/05/2020 18:22:47,Hombre,22,Virgo,Estudiante ingeniería electrónica,50000.0,100000.0
131,22/05/2020 18:22:53,Mujer,35,Géminis,estudiante de postgrado,80000.0,120000.0
132,22/05/2020 18:22:56,Hombre,25,Capricornio,Desarrollador de Software,60000.0,90000.0
133,22/05/2020 18:23:06,Hombre,39,Sagitario,sistemas,60000.0,90000.0
134,22/05/2020 18:23:08,Hombre,27,Cáncer,abogado,35000.0,70000.0
135,22/05/2020 18:23:11,Prefiero no decirlo,40,Leo,Lic,40000.0,80000.0
136,22/05/2020 18:23:31,Hombre,41,Géminis,Sistemas,50000.0,110000.0
137,22/05/2020 18:23:33,Mujer,33,Aries,psicologa,70.0,90.0
138,22/05/2020 18:23:34,Hombre,31,Géminis,Ing. en Sistemas,45000.0,60000.0
139,22/05/2020 18:23:45,Prefiero no decirlo,25,Picis,Ingenieria,70000.0,100000.0
140,22/05/2020 18:23:50,Otro,17,Picis,estudiante,35000.0,150000.0
141,22/05/2020 18:23:58,Hombre,25,Capricornio,Programador,40000.0,75000.0
142,22/05/2020 18:24:10,Hombre,26,Acuario,Desarrollador,50000.0,70000.0
143,22/05/2020 18:24:44,Mujer,32,Cáncer,Profesora,45000.0,50000.0
144,22/05/2020 18:25:01,Hombre,49,Aries,Ingeniero de Software,40000.0,55000.0
145,22/05/2020 18:25:27,Mujer,62,Aries,Arquitecta,60000.0,80000.0
146,22/05/2020 18:25:58,Hombre,33,Libra,"Estudiante, programador",60000.0,80000.0
147,22/05/2020 18:26:04,Hombre,35,Picis,Desarrolador,50000.0,150000.0
148,22/05/2020 18:28:19,Mujer,36,Géminis,Docente,50000.0,100000.0

In [6]:
df.timestamp

0      31/03/2020 17:10:01
1      12/05/2020 15:19:14
2      13/05/2020 13:43:48
3      13/05/2020 18:12:04
4      14/05/2020 16:30:09
5      14/05/2020 19:46:32
6      14/05/2020 19:46:57
7      14/05/2020 19:49:24
8      14/05/2020 19:53:12
9      14/05/2020 19:54:35
10     14/05/2020 19:57:29
11     14/05/2020 20:00:52
12     14/05/2020 20:17:37
13     14/05/2020 20:29:10
14     14/05/2020 20:41:58
15     14/05/2020 21:06:36
16     14/05/2020 21:10:10
17     14/05/2020 21:16:43
18     14/05/2020 21:40:58
19     14/05/2020 21:41:22
20     14/05/2020 21:56:20
21     14/05/2020 21:58:39
22     14/05/2020 22:12:19
23     14/05/2020 22:27:18
24     14/05/2020 22:55:06
25     14/05/2020 23:04:03
26      15/05/2020 7:41:14
27      15/05/2020 8:56:45
28      15/05/2020 9:10:49
29      15/05/2020 9:11:50
              ...
119    22/05/2020 18:21:54
120    22/05/2020 18:22:06
121    22/05/2020 18:22:07
122    22/05/2020 18:22:13
123    22/05/2020 18:22:17
124    22/05/2020 18:22:20
125    22/05/2020 18:22:23
126    22/05/2020 18:22:25
127    22/05/2020 18:22:32
128    22/05/2020 18:22:34
129    22/05/2020 18:22:40
130    22/05/2020 18:22:47
131    22/05/2020 18:22:53
132    22/05/2020 18:22:56
133    22/05/2020 18:23:06
134    22/05/2020 18:23:08
135    22/05/2020 18:23:11
136    22/05/2020 18:23:31
137    22/05/2020 18:23:33
138    22/05/2020 18:23:34
139    22/05/2020 18:23:45
140    22/05/2020 18:23:50
141    22/05/2020 18:23:58
142    22/05/2020 18:24:10
143    22/05/2020 18:24:44
144    22/05/2020 18:25:01
145    22/05/2020 18:25:27
146    22/05/2020 18:25:58
147    22/05/2020 18:26:04
148    22/05/2020 18:28:19
Name: timestamp, Length: 149, dtype: object

In [7]:
df['age']

0      27
1      40
2      22
3      23
4      33
5      29
6      36
7      28
8      39
9      28
10     33
11     29
12     25
13     36
14     30
15     27
16     26
17     25
18     27
19     36
20     28
21     27
22     47
23     26
24     30
25     39
26     42
27     46
28     51
29     23
       ..
119    28
120    30
121    31
122    55
123    52
124    27
125    25
126    27
127    24
128    60
129    49
130    22
131    35
132    25
133    39
134    27
135    40
136    41
137    33
138    31
139    25
140    17
141    25
142    26
143    32
144    49
145    62
146    33
147    35
148    36
Name: age, Length: 149, dtype: int64